### ISSUE TITLE
How can I recur the forecasting section in your paper?

### ISSUE THREAD

**Issue by PericlesHat** [Logan-Shi/GPDM-trajectory-generation#1]
Hi,

In the paper `Gaussian Process Dynamical Model` , GPDM can predict the rest frames based on the given frames. May I ask how to recur it on the codes you provide? Or is there a demo file? Thank you so much.

Cite: Wang, J. M., Fleet, D. J., Hertzmann, A. [Gaussian Process Dynamical Models](http://www.dgp.toronto.edu/~jmwang/gpdm/nips05final.pdf). In Proc. NIPS 2005. December, 2005. Vancouver, Canada. pp. 1441-1448.

**Comment by Logan-Shi** [comment]
Hello,

Regarding your question, maybe you can try running `recontruction.m` with the given 'samples.mat'. Rest frames are predicted using the 2nd order model. 

Actually, I am not the author of the paper. If you want a more detailed discussion, you can go to [the original site](http://www.dgp.toronto.edu/~jmwang/gpdm/) where more informations on the paper (including the source code) are provided.
